# Site settings
title: Jon Albo
description: Jon Albo's portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Jon Albo, PhD
user_title: 
user_job_title: Data Scientist + Project Manager
email: jonalbo311@gmail.com


exclude: ['package.json', 'src' , 'node_modules']
